### ISSUE TITLE
add a character to the characters section (eg Neo, Trinity, etc)

### ISSUE THREAD

**Issue by roannav** [roannav/matrix-movies-website-hacktoberfest#1]
WHO: Hello, this task is perfect for beginner developers, who just know some HTML or are trying to learn how to use GitHub.

WHAT: The task is to add a character (eg Neo) to the list of characters that show up on the web page.

IMPORTANT: To avoid merge conflicts, each pull request should update only 1 person character. So in other words, 1 pull request for Neo. Then another pull request for Trinity and so on.

10/6/2023 update: Still many characters to choose from including: 
The Oracle, Switch, Tank, Dozer, Spoon Boy, Apoc, Agent Brown, Agent Jones, White Rabbit, Choi, Mouse, The Architect, Axel, Bane, Ghost, Jax, The Keymaker, Link, Lock, The Merovingian, Niobe, Roland, Seraph, Sati, The Trainman, Bugs, and The Analyst.

# Steps to complete the task

1. Type `git pull` in a console Terminal to make sure you have the most up-to-date code from this repo.
2. Open `index.html` in a text editor
3. Find the code `<div class="characters-section">`
4. Inside of this `<div class="characters-section"></div>` element, is where you'll add your code.   The characters are listed **alphabetically** by their **character-name**.
5. Your code will look like this
```
<div class="character">
  <h4>Name: {character-name}</h4>
  <img src="img/characters/person-avatar-placeholder.png" alt="{character-name}" />
  <p>AKA: {character-other-names}</p>
  <p>Quotes: {quote the character said} </p>
</div>
```
6. Be sure to replace the placeholders `{}` with the real data for the character you are adding (eg Neo, Morpheus, The Architect, etc).

Complete example: 
`{character-name}` is replaced by `Neo`.
`{character-other-names}` is replaced by `Mr. Anderson or Thomas Anderson`
`{quote the character said}` is replaced by `When Trinity says "Neo, no one has ever done anything like this.", then Neo replies "That's why it's going to work."`

So here's the complete code:
```
<div class="character">
  <h4>Name: Neo</h4>
  <img src="img/characters/person-avatar-placeholder.png" alt="Neo" />
  <p>AKA: Mr. Anderson or Thomas Anderson</p>
  <p>Quotes: When Trinity says "Neo, no one has ever done anything like this.", then Neo replies "That's why it's going to work."</p>
</div>
```

7. If you don't have the character's other names and/or famous quotes, then just leave the code as is.
Someone else may edit that code in the html page later.

8. Bonus optional step: Find a photo of the character on the Internet.  Place the photo in the `/img/characters` folder of your repo.  Modify the code above where it says `<img src="img/characters/person-avatar-placeholder.png" alt="Neo" />`  so that it uses the filename of the photo you added to the `/img/characters/` directory.

**Comment by ombhagwat2401** [comment]
Hello @roannav I am interested in this task
Can you assign it to me?
And can you explain me in more detail?

**Comment by barkhayadav12** [comment]
Hi, I would like to work on this. Can you assign it to me?

**Comment by roannav** [comment]
Hi @ombhagwat2401 and @barkhayadav12, thanks for your interest in this issue!   

To avoid merge conflicts, each pull request should update only 1 person character.  So in other words, 1 pull request for Neo.  Then another pull request for Trinity and so on.

> Hello @roannav I am interested in this task Can you assign it to me? And can you explain me in more detail?

@ombhagwat2401 I updated the issue to contain more step by step instructions.  If that doesn't answer your questions, please let me know.

**Comment by Naman73598** [comment]
Hey @roannav , i would like to work in the issue #1. Assign this to me.
#hacktoberfest2023

**Comment by roannav** [comment]
@Naman73598 Thank you for your interest on working on this issue!  You have been assigned.

**Comment by Aadhithya-R-P** [comment]
Hey @roannav I'd like to contribute to this issue. Can you assign this to me?

**Comment by Santanagamael** [comment]
Hey @roannav , i would like to work in the issue. Assign this to me.
#hacktoberfest2023

**Comment by 13sam** [comment]
hey I would like to work on this issue

**Comment by roannav** [comment]
@Santanagamael and @13sam You've been assigned.  Thank you and Happy coding!

**Comment by roannav** [comment]
@Santanagamael and @13sam Unfortunately, I need to close this issue, because it may be not hacktoberfest friendly, so please don't make a pull request for this issue.
