### ISSUE TITLE
BUG: Make the Page heading for "Photo Gallery" and "Wallpapers" look like the animated glowing one in "Plots".

### ISSUE THREAD

**Issue by roannav** [roannav/matrix-movies-website-hacktoberfest#106]
If you look at [plot.html](https://roannav.github.io/matrix-movies-website-hacktoberfest/plot.html), you can see how Plots is glowing and animates in a loop.

All the other pages have page titles with the same animated glowing style, except for "Photo Gallery" and "Wallpapers". 

gallery.html has the wrong heading.

wallpapers.html is missing a heading.

**Comment by sagarb2003** [comment]
Assign me this issue also can u elaborate more about this issue

**Comment by roannav** [comment]
Hi @sagarb2003,  This issue is pretty simple.  Each correct page has a page title that is contained in an `<h3>` heading.    But has the wrong or missing heading for gallery.html and wallpapers.html
