### ISSUE TITLE
BUG: accordion in games.html is not opening

### ISSUE THREAD

**Issue by roannav** [roannav/matrix-movies-website-hacktoberfest#107]
The [games.html](https://roannav.github.io/matrix-movies-website-hacktoberfest/games.html) has text, photo, and video content.  When you click on the accordion, it should open to show the content, but it's not working now.

See [plot.html](https://roannav.github.io/matrix-movies-website-hacktoberfest/plot.html) for an example of a working accordion.

**Comment by strive79** [comment]
assign this to me , I will work on this

**Comment by roannav** [comment]
Thank you @Shubhangam333 you're assigned to this issue.

**Comment by strive79** [comment]
#112 Raised PR for this fix
