### ISSUE TITLE
BUG: For mobile screen widths, the accordion is too wide in the Games page

### ISSUE THREAD

**Issue by roannav** [roannav/matrix-movies-website-hacktoberfest#129]
To reproduce this bug, use a mobile device or resize your browser to less than 650px width.   

If you go to [games.html](https://roannav.github.io/matrix-movies-website-hacktoberfest/games.html), 
then you'll see that the accordion extends beyond the right and left edges of the screen.
At smaller mobile widths the words are cut off.

Note: [plot.html](https://roannav.github.io/matrix-movies-website-hacktoberfest/plot.html) also uses similar accordions, but this time it does resize the accordion (and the title wraps to the next line) at smaller screen widths.  This is better and games.html's accordions should act like this.

**Comment by P-Jaswanth** [comment]
Hey, I would like to work on this. Please assign this to me

**Comment by roannav** [comment]
@P-Jaswanth Thanks!  You're assigned to this issue.

**Comment by ayushkumarTomar** [comment]
Hey , I fixed that issue . Please merge the pull request
