### ISSUE TITLE
BUG: for mobile or middle screen widths, the cast section is too wide

### ISSUE THREAD

**Issue by roannav** [roannav/matrix-movies-website-hacktoberfest#130]
To reproduce this bug, use a mobile device or resize your browser to less than 900px width.

If you look at  [cast-crew.html](https://roannav.github.io/matrix-movies-website-hacktoberfest/cast-crew.html), 
then you'll see a number of problems:
-  the top section (ie the Cast section) extends beyond the right edge of the page.
-  note that the scrollbar on the right side of the Cast section is beyond the right edge of the page.
- At smaller mobile widths (eg 500px), the headings "Character Role" and "Actor's Name" are cut off, so these headings might need to use a smaller font or be placed closer together.

Please take a look at `css/pages/cast-crew.css`:
```
.cast-section {
   width: 900px;   /* This is a problem for mobile devices */
}
```
When fixing this bug, please check that it still looks good for desktop widths.

**Comment by Virtual4087** [comment]
I would like to work on this issue. Can you assign it to me?

**Comment by roannav** [comment]
Hi @Virtual4087 Thank you for your interest in this issue.  You're assigned.
