### ISSUE TITLE
BUG: For mobile screen widths, in scenes.html, the `<h2>` green background color doesn't cover all the text

### ISSUE THREAD

**Issue by roannav** [roannav/matrix-movies-website-hacktoberfest#131]
To reproduce this bug, use a mobile device or resize your browser to less than 600px width.

If you go to [scenes.html](https://roannav.github.io/matrix-movies-website-hacktoberfest/scenes.html),
then you'll see that the heading "Some pictures from The Matrix series" wraps to 2 lines.
Also further down the same page, you'll see that the heading "Some videos from The Matrix series" wraps to 2 lines.

In both cases, the green background only covers 1 line, not 2 lines of text, like it should.

**Comment by strive79** [comment]
Hey, I would like to work on this one, Assign this to me

**Comment by roannav** [comment]
Thanks @Shubhangam333 you're assigned to the task.

**Comment by strive79** [comment]
#134 : Raised PR for the same
