### ISSUE TITLE
BUG: For mobile and middle screen widths, the vertical space after `</p>` tags disappear in the Terms of Use and the Privacy Policy pages

### ISSUE THREAD

**Issue by roannav** [roannav/matrix-movies-website-hacktoberfest#133]
To reproduce this bug, use a mobile device or resize your browser to less than 760px width.

If you go to [terms-of-use.html](https://roannav.github.io/matrix-movies-website-hacktoberfest/terms-of-use.html) and to [privacy-policy.html](https://roannav.github.io/matrix-movies-website-hacktoberfest/privacy-policy.html),
then you'll see that all the vertical spaces between the paragraphs are missing.

When fixing this bug, please check that the vertical spacing between paragraphs still looks good for desktop widths.

**Comment by strive79** [comment]
Hi , I would like to work on this Issue

**Comment by roannav** [comment]
@Shubhangam333 Thank you, you're assigned

**Comment by strive79** [comment]
#136 raised for issue #133 and #135
