### ISSUE TITLE
The More Info button of the "Woman in Red" redirects to the wrong wiki page

### ISSUE THREAD

**Issue by ElectroCubic** [roannav/matrix-movies-website-hacktoberfest#146]
Also the Name heading for the "Woman in Red" is displaying the wrong name (Morpheus)

![Screenshot 2023-10-27 183301](https://github.com/roannav/matrix-movies-website-hacktoberfest/assets/145821463/867f1ebd-2aa4-4159-8b6e-b524a864d5a1)

**Comment by ElectroCubic** [comment]
@roannav Please assign me this issue so I can improve the Characters.html page and add the Hacktoberfest label to it

**Comment by roannav** [comment]
Thank you @ElectroCubic, you're assigned to this issue

**Comment by roannav** [comment]
Fixed in PR #152
