### ISSUE TITLE
Improve navbar

### ISSUE THREAD

**Issue by sai-kumar0** [roannav/matrix-movies-website-hacktoberfest#155]
Hey @roannav 
 
I have visited the website and found small bug. 

![Screenshot 2023-10-29 155708](https://github.com/roannav/matrix-movies-website-hacktoberfest/assets/129689787/aa3abd43-4d60-44f0-9851-39d5f0cdbd26)

As you can see in the above picture the width of the navbar is exceeded.  If we manage the width to the same as its container it will enhance the quality and improves user experience.

**Comment by roannav** [comment]
Hi @sai-kumar0, Thanks for spotting this bug!  I've assigned you to this task.

**Comment by sai-kumar0** [comment]
hey @roannav 

I have fixed the navbar. 

Here is the link of the fixed website. Try check it and text me if there are any issues

https://sai-kumar0.github.io/matrix-movies-website-hacktoberfest/

![image](https://github.com/roannav/matrix-movies-website-hacktoberfest/assets/129689787/2e6709e0-a257-4d67-bf54-49bc1b9cf0fa)
