### ISSUE TITLE
Adding some css styles in the page

### ISSUE THREAD

**Issue by charmee123** [roannav/matrix-movies-website-hacktoberfest#16]
Hi there, 
It would be better to change the styling of the page to make matrix website more attractive. I want to change the alignment of the text, color, font style and want to add some padding. @roannav It would be better if you assign this to me so that I will try to make website more attractive. Please feel free to contact me.

**Comment by roannav** [comment]
Hi @charmee123,  That would be terrific, if you want to improve the style of the website!  What ideas do you have?  It's currently a dark theme with greenish highlights.   I considered changing the font of the large text to [Orbitron - Google Fonts](https://fonts.google.com/specimen/Orbitron/about?preview.text=Characters&preview.text_type=custom),  but there are other interesting fonts as well.  Please describe in more detail what you would like to do.  Thanks!

**Comment by charmee123** [comment]
Thanks for replying @roannav . I want to change alignment of headings to the center, want to add little bit padding between character name and image so that it can look decent. And it would be also better to move image in the center with little bit of radius in the image. I also thinking to change heading font family to 'Arvo", cursive;'. I have noticed to change these things please let me know your ideas and what you think on these points. Thanks.

**Comment by roannav** [comment]
Hey @charmee123,   Your ideas sound good to me!  Arvo is an interesting font, better than the current one.   Were you planning to go with an italic or bold version of Arvo?  I'm thinking cursive-handwritten style doesn't match the vibe of the movie though.

**Comment by charmee123** [comment]
Hi @roannav , Arvo bold with 700 font weight will be fine and heading should be written in capital so that it looks little classy.

**Comment by roannav** [comment]
I like bold and in capital letters.  Sounds great, @charmee123 Looking forward to seeing your changes in the website :smile:   Thank you for your help!

**Comment by charmee123** [comment]
Thanks for assigning the issue @roannav . I am new to open source and it's my first contribution so want to confirm that I need to follow the steps that you have listed in readme file for contribution, right?

**Comment by roannav** [comment]
@charmee123 Yes, please follow the README.md steps.  They are a common pattern of fork-clone-branch that is done for open source contributions.   
Please ask me questions if you run into any problems.

By the way, if you have already done the fork-clone-branch, before 1 hour ago, then you should grab the latest code from the repo, since it has changed in the last hour.
```
cd matrix-movies-website-hacktoberfest
git checkout main
git pull
git checkout <your-branch-name>
git merge main
```
This will grab the latest code from the main repo at GitHub and put into your branch on your computer.

**Comment by roannav** [comment]
If you haven't done the fork-clone-branch yet, then you don't need to do the additional steps.

**Comment by charmee123** [comment]
Hi @roannav, I have modified style sheet and made a pull request (I am not sure if I done it right) Please look it once and merge it. Happy to contribute in this repo 😃

**Comment by roannav** [comment]
Hi @charmee123,  thank you for all the work you put into improving the design of the website.  It looks awesome!   I especially like the way the main title looks! 🥳
