### ISSUE TITLE
Adding Footer to the Web Page

### ISSUE THREAD

**Issue by Sujal-2820** [roannav/matrix-movies-website-hacktoberfest#18]
Hey @roannav, I would Like to add a Footer to the Web page in order to make it appearance of the website look good. 
Please label this issue as "Hacktoberfest 2023" and assign this to me 🙂.

You can also suggest me some elements needed to be added in particular..

**Comment by roannav** [comment]
@Sujal-2820 Good idea!  Thank you for creating this issue. The header could include:

```
Contributions from anyone to this website are welcome!  Please see the [Matrix Movies Website GitHub Repo](https://github.com/roannav/matrix-movies-website-hacktoberfest)

This website is licensed under the terms of the MIT license.
By using this site, you agree to the [Terms of Use](terms-of-use.html) and [Privacy Policy](privacy-policy.html).
```

I wrote the links in Markdown above, but they should be converted to HTML `<a href=...` links.

Do you think anything else should go in the header?

**Comment by Sujal-2820** [comment]
Thanks @roannav for assigning me the issue. I'll just hop into the code and add the requirements and I would inform you about any possible additions which would go well with the Layout.

**Comment by Sujal-2820** [comment]
Hello @roannav,
Can you review the changes in Header once.

Attached is the image of the changes.

Please tell me if I can go ahead with the pushing the code, or you wish to have some more additions to it..

![image](https://github.com/roannav/matrix-movies-website-hacktoberfest/assets/112640952/38065be3-4cac-4a8d-9732-5540d43b8b46)

**Comment by roannav** [comment]
Hi @Sujal-2820, 
Sorry, for the confusion.  I meant footer.    The same content, but in the footer.   Since it's a footer it can visually blend in more with the dark theme of the website.   So perhaps make the footer's background a bit darker than the rest of the website and use white letters.   I like how you made the links larger, so that they stand out more.  Thank you very much for your help to this website!

**Comment by Sujal-2820** [comment]
No problem @roannav. I will shift changes to the footer. 
Thanks for the appreciation 🙂

Let me know if you need any more additions 💯

**Comment by Sujal-2820** [comment]
I have arranged the Layout of Footer in various ways.

@roannav please inform me which one is looking good:

**First**
![image](https://github.com/roannav/matrix-movies-website-hacktoberfest/assets/112640952/76423f0f-c0dd-40a4-8f76-c3de5e3d4c4e)

**Second**
![image](https://github.com/roannav/matrix-movies-website-hacktoberfest/assets/112640952/3a0976fe-44f8-4fbb-9d3a-c5feccb4afec)

**Third**
![image](https://github.com/roannav/matrix-movies-website-hacktoberfest/assets/112640952/72f1a77e-e573-4be1-871e-6c2a4fc411a5)

**Fourth (Inside Credits Section):**
![image](https://github.com/roannav/matrix-movies-website-hacktoberfest/assets/112640952/0efa16b4-6887-44d1-abd3-8a289eed043f)

**Comment by roannav** [comment]
@Sujal-2820   It's getting better!   I like the bright green links of the 4th one, because the color contrast makes it more readable.  Please leave the footer OUTSIDE of the Credits.   It could be nice to make the `<footer>` section a bit darker by writing this CSS:

```
footer {
  background-color: #00000050;
}
```

**Comment by Sujal-2820** [comment]
Sure @roannav. I would implement the required changes and send you a snip of the same

**Comment by Sujal-2820** [comment]
@roannav how about this? I changed the background color to be "#00000050" as well

![image](https://github.com/roannav/matrix-movies-website-hacktoberfest/assets/112640952/593211b9-385e-4a73-bf93-3f97a73a07b0)

**Comment by roannav** [comment]
@Sujal-2820 Looks great!

**Comment by Sujal-2820** [comment]
Thanks @roannav!! 😄
Shall I push the changes ?

**Comment by roannav** [comment]
@Sujal-2820 Yes, thanks! :smile:

**Comment by Sujal-2820** [comment]
@roannav, please review the PR
https://github.com/roannav/matrix-movies-website-hacktoberfest/pull/27#issue-1931681373
