### ISSUE TITLE
Add CONTRIBUTING.md file to Repository

### ISSUE THREAD

**Issue by Sujal-2820** [roannav/matrix-movies-website-hacktoberfest#23]
@roannav, I think your repository should contain CONTRIBUTING.md file (as seen in many projects participating in Hacktoberfest) in order to get recognized in Hacktoberfest.

You can either add it by yourself or assign this issue to me to add the File 🙂

Also please label this issue as "hacktoberfest".

**Comment by roannav** [comment]
Thank you for contributing the CONTRIBUTING.md !  :smile:
