### ISSUE TITLE
navigation bar

### ISSUE THREAD

**Issue by roannav** [roannav/matrix-movies-website-hacktoberfest#29]
A horizontal navigator bar with links to go to the other main pages in the website.
Place navbar just below the `<header>`

### Items in the navbar:
- Characters (links to characters.html)
- Plot (links to plot.html)
- Favorite Scenes (links to scenes.html)
- Cast & Crew (links to cast-crew.html)
- Reviews (links to reviews.html)
- Games (links to games.html)

These html pages will be created soon.

**Comment by Rhythmshah21** [comment]
@roannav i would like to work on this issue

**Comment by Rhythmshah21** [comment]
![image](https://github.com/roannav/matrix-movies-website-hacktoberfest/assets/102286539/bee1751f-b309-4065-99ee-8edf82e3275d)
what Else do u need?

**Comment by roannav** [comment]
If you want you could add some styles to it, and also style when you hover over it.

**Comment by Rhythmshah21** [comment]
Yes Done, you can now see it

**Comment by Wafmulla** [comment]
Can you assign this task to me?

**Comment by roannav** [comment]
@Wafmulla I am closing this issue since it is done.  I have a new issue #38 that you might be interested in.  Please take a look and see if you would like to work on that issue.  Thank you :smile:
