### ISSUE TITLE
improve text: fix typos, grammar mistakes, inaccurate text content

### ISSUE THREAD

**Issue by roannav** [roannav/matrix-movies-website-hacktoberfest#33]

**Comment by ezhillragesh** [comment]
Hi @roannav ,

Is it possible to assign this issue to me? I believe I can help in addressing the problem and working towards a solution. 

Looking forward to your response.

Best regards,
Ezhill Ragesh

**Comment by roannav** [comment]
Hi @ezhillragesh, Thanks for your interest in this issue.  You've been assigned. :smile:

**Comment by ezhillragesh** [comment]
I have created a PR for the improvements
