### ISSUE TITLE
improve navbar

### ISSUE THREAD

**Issue by roannav** [roannav/matrix-movies-website-hacktoberfest#38]
The code for the navbar is in `js/navbar.js`

You can see how it runs now by going to [link](https://roannav.github.io/matrix-movies-website-hacktoberfest/reviews.html)
It has a nice transition effect already that would be good to keep.

This task is to
1) make the navbar responsive, so on mobile phones, all of the word links are replaced by the 3 line hamburger symbol.  Then if you click on the hamburger menu, it'll show the links stacked vertically, instead of horizontally.
2) make links look like buttons.  Specifically the background color could be #00000050.  Then when the link is active and the user is on that page, the background color is a kind of green.

What I'm looking for is similar to this:  [How To Create a Responsive Top Navigation Menu](https://www.w3schools.com/howto/howto_js_topnav_responsive.asp)

**Comment by VikeshKumar64** [comment]
Please assign it to me .

**Comment by roannav** [comment]
Hi @Wafmulla  Please take a look at this similar issue and see if you would like to work on it.  Let me know if you want  to be assigned.  Thanks!

**Comment by Wafmulla** [comment]
yes sure i would like to work on this issue. Should i start working on it?

**Comment by himanchal08** [comment]
i would like to work on this issue it seems
i will try my best to implement it
i don't have much idea of code so i'll need help
if you think i can do the job please assign it to me i do have basic knowledge of html css and js

**Comment by roannav** [comment]
Hi @Wafmulla you've been assigned.  Thank you for offering to work on it!
