### ISSUE TITLE
style the reviews-section in the Reviews page

### ISSUE THREAD

**Issue by roannav** [roannav/matrix-movies-website-hacktoberfest#39]
Please see the [reviews.html](https://roannav.github.io/matrix-movies-website-hacktoberfest/reviews.html) page.

Things such as font, font size, font weight, spacing, alignment, or something else could be changed to make it look better.

Styles that are for the Reviews page should go into css/pages/reviews.css. They will override anything in css/default.css.

Please add style to ONLY the content inside of `<section class="reviews-section">`

Please do NOT change the other parts of the page, like the header, navbar, or footer, since I want that consistent between all the pages.  Yes, it doesn't currently look the same, but a DIFFERENT issue will fix that.

**Comment by Aka-suvam** [comment]
Hello @roannav  i like to work on this issue . Can you  assign this issue to me .

**Comment by ShrutiSingh04503** [comment]
Hye @roannav I want to work on this issue, Please assign me this issue

**Comment by roannav** [comment]
Hi @Aka-suvam since you commented first, you've been assigned.  Thank you!

**Comment by daemonX10** [comment]
bro , since it been 3 days can you give chance to me ? assign me ?

**Comment by roannav** [comment]
Hi @Aka-suvam, I'm wondering if you started working on this issue?   If so, I'll wait for your contribution.   If not, another person already made a pull request for this issue that I could merge in and so I could assign you to another issue instead, if you'd like. 
 Please let me know within 24 hours or else I will merge the pull request.   Thanks.

**Comment by TheShiveshNetwork** [comment]
Can you assign this to me too? @roannav

**Comment by Aka-suvam** [comment]
> Hi @Aka-suvam, I'm wondering if you started working on this issue? If so, I'll wait for your contribution. If not, another person already made a pull request for this issue that I could merge in and so I could assign you to another issue instead, if you'd like. Please let me know within 24 hours or else I will merge the pull request. Thanks.

@roannav . I have not started . you can Merge the PR . I was thinging to contriubute  today . but someone alredy made PR .  
Thank u .

**Comment by roannav** [comment]
@Aka-suvam Thanks for getting back to me.  Are you interested in another issue?

**Comment by Aka-suvam** [comment]
@roannav . If there is a beginner issue. plz assign me . I know basic HTML/CSS . Also love the idea and the Website  (The Matrix-).   
Thnk u .

**Comment by Wafmulla** [comment]
Hey can you please assign this issue to me under Hacktoberfest 2023 label?

**Comment by roannav** [comment]
@Wafmulla Thank you for offering to help.  While you are working on this issue, please make the header, navbar, and footer look the same as the other pages on the website.  The header, navbar, and footer styles are already defined in default.css.  So you will need to remove some of the new styles that were added to reviews.html, that are overriding default.css.  We want it to look like the header, navbar, and footer defined in default.css.

Styles that are for the Reviews page should go into css/pages/reviews.css.   They will override default.css.

**Comment by roannav** [comment]
Hi @Wafmulla, Thank you.  Please ignore my last message about the header, navbar and footer.   Instead see the updated task at the top.  https://github.com/roannav/matrix-movies-website-hacktoberfest/issues/39#issue-1933650775

**Comment by daemonX10** [comment]
here is some i thought what to be done ,
make navbar in single line by using (display flex and align) and/or  a button on which clicking navbar open .
in review section , make prev button to scroll button or/and button on at the start of right and left side.  click on it to see another review .
and auto change review in 10 second. 
Make body section 100% of page .
add hover effect .
color combination  : #A5FFC9  and  #A5C9FF

**Comment by Wafmulla** [comment]
> Hi @Wafmulla, Thank you. Please ignore my last message about the header, navbar and footer. Instead see the updated task at the top. [#39 (comment)](https://github.com/roannav/matrix-movies-website-hacktoberfest/issues/39#issue-1933650775)

Yes sure I will start working on it.

**Comment by roannav** [comment]
@MrLEGENDx10 Many good ideas here!   

> make navbar in single line....

No need to modify the navbar, since that is being taken care of in issue #79 

>  in review section , make prev button to scroll button or/and button on at the start of right and left side.

How do you mean?  

Like this?   ... where the previous button is just to the left of the review text and the next button is just to the right of the review text?
![image](https://github.com/roannav/matrix-movies-website-hacktoberfest/assets/11859151/3d8f9909-7de7-4e6a-819e-d317a69325df)


> auto change review in 10 second. Make body section 100% of page . add hover effect . color combination : #A5FFC9 and #A5C9FF

Great!

**Comment by daemonX10** [comment]
Yes

**Comment by harshit1142** [comment]
I can improve it more. Can you assign this to me ?
