### ISSUE TITLE
favourite scenes page: initial layout

### ISSUE THREAD

**Issue by roannav** [roannav/matrix-movies-website-hacktoberfest#40]
Here is the current [favourite scenes page](https://roannav.github.io/matrix-movies-website-hacktoberfest/scenes.html).

This page will contain many rows of thumbnails (ie smaller versions) of pictures or videos.
For coding purposes, you can use a div or placeholder image, instead of real images.
Each picture or video should be limited to a max-height.

Each row looks something like this:
![Screenshot from 2023-10-09 12-40-51](https://github.com/roannav/matrix-movies-website-hacktoberfest/assets/11859151/2cd9b293-c67a-46d9-8e97-d9b523858324)

One way to achieve the task is to add a flexbox of these image items.  The flexbox container allows wrap.
CSS can be added to styles.css

**Comment by om453** [comment]
assign me this issue i want to work on it @roannav

**Comment by roannav** [comment]
Thank you @om453 You've been assigned.
