### ISSUE TITLE
fix: Directory Structure

### ISSUE THREAD

**Issue by susanhsrestha** [roannav/matrix-movies-website-hacktoberfest#53]
The project directory looks very messy. You can refactor and make adjustments to make the folder structure and hierarchy to make it look better and standard.

**Comment by roannav** [comment]
Hi @susanhsrestha, 

Would you be willing to:
1) move poster*.jpg into img/home/movie-poster/
2) move photo*.jpg into img/gallery/
3) Then update index.html and gallery.html so everything links to the updated locations

There is another contributor who is moving styles.css into styles/

**Comment by susanhsrestha** [comment]
Sure

**Comment by susanhsrestha** [comment]
is the rotating poster working now?

edit: its working

**Comment by roannav** [comment]
@susanhsrestha Thanks!  You're assigned.

> is the rotating poster working now?

It was working today.  It updates every 5 seconds

**Comment by susanhsrestha** [comment]
@roannav here's the fix I came up with #54
