### ISSUE TITLE
favicons

### ISSUE THREAD

**Issue by roannav** [roannav/matrix-movies-website-hacktoberfest#59]
The Matrix Movies Website could use favicons.
Please choose a drawing or photo that could represent this website and will look good when it's small.

Here's a handy tool:   https://favicon.io/favicon-converter/ will generate all the favicons if you give it an image.

Please put all the favicons into /img/favicons/  instead of the root, so that the root doesn't get crowded with too many files.

Then add code like this to **all** of the html files:   Make sure to update the file paths below.
```
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/site.webmanifest">
```

**Comment by pt21v** [comment]
Hi @roannav , assign to me, please!

**Comment by roannav** [comment]
@ivanetra Thanks!  You're assigned.

**Comment by pt21v** [comment]
> @ivanetra Thanks! You're assigned.

Thanks @roannav !
