### ISSUE TITLE
style the plot-section in the plot.html page

### ISSUE THREAD

**Issue by roannav** [roannav/matrix-movies-website-hacktoberfest#61]
This task is to add some style to the `<section class="plot-section">`
It's a simple accordion with the summaries of the 4 movies.

Please do NOT change the other parts of the page, like the header, navbar, or footer, since I want that consistent between all the pages.

**Comment by roannav** [comment]
Hi @Aka-suvam, I've assigned you this issue.  Please let me know if you want to work on it.

**Comment by vanshiz** [comment]
please assign me this

**Comment by Aka-suvam** [comment]
> This task is to add some style to the `<section class="plot-section">` It's a simple accordion with the summaries of the 4 movies.
> 
> Please do NOT change the other parts of the page, like the header, navbar, or footer, since I want that consistent between all the pages.

@roannav . Thk u for assign me this issue . i will work on this issue .

**Comment by roannav** [comment]
@Aka-suvam Thanks, you're assigned!

**Comment by daemonX10** [comment]
add label to issue , @roannav .

**Comment by Aka-suvam** [comment]
Thnk you soo much .   @roannav  and @MrLEGENDx10 . I sincerely appreciate …
