### ISSUE TITLE
text for Terms of Use

### ISSUE THREAD

**Issue by roannav** [roannav/matrix-movies-website-hacktoberfest#63]
Right now, terms-of-use.html contains ipsum placeholder text.

Please replace this with text that would typically be found in a website's Terms of Use.

Tip:  Google "terms of use generator for website"

**Comment by nishantdub37** [comment]
@roannav can u assign this task to me?

**Comment by roannav** [comment]
@nishantdub37 Thank you!  You've been assigned.
