### ISSUE TITLE
Changing the color of Hover on Links

### ISSUE THREAD

**Issue by Sujal-2820** [roannav/matrix-movies-website-hacktoberfest#69]
Hey @roannav,

I would like to make changes to the hover effect on the links.

Can you assign this issue to me and label it as "Hacktoberfest-accepted"

**Comment by prerit2001** [comment]
Can you assign this issue to me and label it as "Hacktoberfest-accepted"

**Comment by sagarb2003** [comment]
@roannav assign me this issue as this is inactive from last week under hacktoberfest2023

**Comment by roannav** [comment]
Hi @sagarb2003,   For this issue please look at css/default.css which has the "Footer styles".  Currently, when hovering over the links in the footer, it changes from a greenish color to white.    Do you think it would be better, if on hover, the link was made bold and a color like "lightgreen" or "chartreuse"?

**Comment by sagarb2003** [comment]
ok I will do this assign me this issue under hacktoberfest2023

**Comment by roannav** [comment]
Thanks, you're assigned @sagarb2003
