### ISSUE TITLE
For reviews.html page, make header, navbar, and footer look the same as on the other pages 

### ISSUE THREAD

**Issue by roannav** [roannav/matrix-movies-website-hacktoberfest#79]
For the reviews.html page, please make the header, navbar, and footer look the same as the other pages on the website. 

The header, navbar, and footer styles that we want to keep are already defined in css/default.css. 

So you will need to REMOVE some of the new styles that were added to reviews.html, that are overriding css/default.css. 
We want it to look like the header, navbar, and footer defined in css/default.css.

All pages use the styles in css/default.css.  
For the reviews.html page, the styles that are in css/pages/reviews.css will override the styles in css/default.css.

**Comment by Shreshth-Srivastava** [comment]
Hello there, I would like to solve this issue so please assign this to me.

**Comment by roannav** [comment]
Hi @Shreshth-Srivastava, Thank you for your interest in this issue.  You are assigned.

**Comment by Shreshth-Srivastava** [comment]
I have made the required changes in the files. 
This is a preview of the page after the changes, if everything looks fine then tell me and I will create a pull request for this issue.

https://github.com/roannav/matrix-movies-website-hacktoberfest/assets/134348598/78acc95f-64b1-40ee-8689-306ac8a132d1

**Comment by roannav** [comment]
@Shreshth-Srivastava Looks great!  Thank you and please make the pull request.  :smile:
