### ISSUE TITLE
Adding Information about a matrix game

### ISSUE THREAD

**Issue by Shreshth-Srivastava** [roannav/matrix-movies-website-hacktoberfest#88]
Hello there, I would like to add description, images etc. about **"The Matrix Awakens"** game in the **"Games"** page.
Please assign me this issue with the **"hacktoberfest"** label so that I can start working on this.

**Comment by roannav** [comment]
@Shreshth-Srivastava That's a great idea!  You're assigned. Thank you for you help!

**Comment by Shreshth-Srivastava** [comment]
@roannav 
Hey there,
I have added info about three video games based on the matrix movies. I have made it similar to plot page so as keep the whole website **uniform**. However, I have introduced slight change in the **styling** of the **bold text**, that is, I have changed their color to **light green** from **white** as in the case of plot page, if you wish to keep the old styling or want any other changes then just tell me and I will apply them.
I have attached a preview of the games.html page.

https://github.com/roannav/matrix-movies-website-hacktoberfest/assets/134348598/31e7b684-8886-43a5-8a40-8bec0159d07c

**Comment by Shreshth-Srivastava** [comment]
If everything is alright then tell me and I will create a pull request for this issue.

**Comment by roannav** [comment]
Hi @Shreshth-Srivastava,   Excellent work!   I appreciate that you found images, video and text description for all 3 games and that you were thoughtful about keeping the design consistent with another part of the website.  Changing the bold text to light green is a nice touch.  Please make a pull request for this.  :100:
