### ISSUE TITLE
Assets optimizations and addition of some better fonts with minor UI changes

### ISSUE THREAD

**Issue by aditya4567uk** [roannav/matrix-movies-website-hacktoberfest#89]
Hi there

assets are too heavy i can add same assets in optimized format with lazy-loaders and less size , which which reduce poor bandwidth issue and IMPROVE WEBSITE SPEED.

I can more readable FONTS for better looks and readability.

And some other UI changes to make website better.

Could you pls assign me this topic.

**Comment by roannav** [comment]
Hi @aditya4567uk,

Thank you for your interest in developing this website project.

Optimizing assets and lazy loading is a beneficial idea.

What fonts do you suggest?

What other UI changes are you considering?

**Comment by aditya4567uk** [comment]
Source code pro font would be great as it's a matrix website so it resemble with some hacker / computer nerd vibes.

another thing i would like make few of the sections a little small , as it looks to big to occupy space on webpage. right amount of length and breadth should be given

What you say? should I work?

**Comment by roannav** [comment]
Yes, I'm interested to see you develop your ideas.  Thank you!

**Comment by aditya4567uk** [comment]
sure thing !
